use_frameworks!

target 'XTStoreKitHelper_Example' do
  pod 'XTStoreKitHelper', :path => '../'

  target 'XTStoreKitHelper_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
	pod 'OpenSSL', '~> 1.0'
  end
end
